---
- name: Ensure that the nscd package is installed
  tags: nscd
  become: true
  yum:
    name: nscd
    state: present
    update_cache: yes
  register: nscd_yum

- block:
    - name: Applying nscd.conf configurations
      template:
        src: nscd.conf.j2
        dest: /etc/nscd.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nscd

    - name: Enable and start the nscd service on boot
      service:
        enabled: yes
        name: nscd
        state: started
  tags: nscd
  become: true
  when: nscd_yum|success
...
