---
- name: Ensure that the nscd package is installed
  tags: nscd
  become: true
  yum:
    name: nscd
    state: present
  register: nscd_yum

- name: Attempting to overlay nscd configurations
  tags: nscd
  become: true
  template:
    src: nscd.conf.j2
    dest: /etc/nscd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nscd
  when: nscd_yum is success

- name: Ensure that nscd is started and enabled on boot
  tags: nscd
  become: true
  service:
    enabled: yes
    name: nscd
    state: started
  when: nscd_yum is success
...
